export const PLAN_CONFIG = {
  starter: {
    name: 'Bench',
    price: 19,
    annualPrice: 15,
    color: '#3b82f6',
    bg: '#eff6ff',
    border: '#bfdbfe',
    icon: '🎓',
    trialDays: 14,
    target: 'Individual researchers, PhD students, postdocs',
    features: [
      { text: 'Up to 5 protocols', included: true },
      { text: '30 runs per month', included: true },
      { text: 'Protocol import (DOCX)', included: true },
      { text: 'Step timer control', included: true },
      { text: 'Deviation logging', included: true },
      { text: 'Basic PDF reports', included: true },
      { text: 'Lot number tracking', included: true },
      { text: 'Expiry date warnings', included: true },
      { text: 'Team members', included: false },
      { text: 'Traceability navigator', included: false },
      { text: '21 CFR Part 11 e-signature', included: false },
      { text: 'Audit View mode', included: false },
    ],
  },
  lab: {
    name: 'Pro',
    price: 79,
    annualPrice: 59,
    color: '#6366f1',
    bg: '#eef2ff',
    border: '#c7d2fe',
    icon: '🔬',
    popular: true,
    trialDays: 21,
    target: 'Research groups, biotech teams, core facilities',
    features: [
      { text: 'Unlimited protocols', included: true },
      { text: 'Unlimited runs', included: true },
      { text: 'Up to 15 team members', included: true },
      { text: 'Team management + invites', included: true },
      { text: 'Role-based access control', included: true },
      { text: 'Traceability navigator', included: true },
      { text: 'Audit readiness score', included: true },
      { text: 'Advanced dashboard + charts', included: true },
      { text: 'Protocol version control', included: true },
      { text: '2-year audit log retention', included: true },
      { text: '21 CFR Part 11 e-signature', included: false },
      { text: 'Audit View mode', included: false },
    ],
  },
  lab_pro: {
    name: 'GMP',
    price: 249,
    annualPrice: 199,
    color: '#dc2626',
    bg: '#fef2f2',
    border: '#fecaca',
    icon: '🏭',
    trialDays: 30,
    target: 'GMP manufacturing, clinical diagnostics, pharma, CRO',
    features: [
      { text: 'Everything in Pro +', included: true },
      { text: 'Unlimited team members', included: true },
      { text: '21 CFR Part 11 e-signature', included: true },
      { text: 'SHA-256 cryptographic hash', included: true },
      { text: 'Inspector-ready Audit View', included: true },
      { text: 'Advanced PDF audit reports', included: true },
      { text: 'Deviation severity management', included: true },
      { text: 'Materials lot traceability', included: true },
      { text: 'Unlimited audit log retention', included: true },
      { text: 'Priority support', included: true },
    ],
  },
};